---
title: "p8105_hw3_bg2645"
author: "Bing Bing Guo"
date: "10/9/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Question 1: 
```{r} 
library(tidyverse)
library(p8105.datasets)
library(dplyr)
data("instacart")
```

* There were `r nrow(instacart)` observations and `r ncol(instacart)` variables in the `instacart` dataset. 
* The key variables in the `instacart` dataset were the names 

```{r} 
instacart %>%
  count(aisle_id, name = "n")%>%
arrange(desc(n))
```
* There are 134 aisles in instacart, the most ordered items are from aisle 83, 24, and 123 respectively - in which aisle 83 had the most ordered items out out of all the aisles. 


```{r}
instacart %>%
count(aisle_id) %>%
filter(n> 10000) %>%
ggplot(aes(x = aisle_id , y = n)) + geom_point() + 
labs(
    title = "Number of Items Ordered in Each Aisle", 
    x = "Aisle",
    y = "Number of Items Ordered (n)",
    caption = "This plot shows the number of items ordered in each aisle, limited to aisles with more than 10,000 items ordered" ) + 
theme(
    plot.title = element_text(hjust = 0.5, size = 14),   
    plot.caption = element_text(hjust = 0, face = "italic")
)
```

```{r} 
top3_data = instacart %>%
filter(aisle %in% c("baking ingredients", "dog food care","packaged vegetables fruits")) %>%
group_by(aisle, product_name) %>%
summarize(n = n()) %>%
top_n(3) %>%
arrange(desc(n)) %>%
knitr::kable()
top3_data
```

```{r} 
instacart %>%
select(product_name, order_dow, order_hour_of_day) %>%
group_by(product_name, order_dow) %>%
summarize(mean_hour = mean(order_hour_of_day)) %>%
mutate(order_dow = recode(order_dow, "0" = "Sunday", "1" = "Monday", "2" = "Tuesday", "3" = "Wednesday", "4" = "Thursday", "5" = "Friday", "6" = "Saturday"))  %>%
filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream"))  %>%
pivot_wider(names_from = "order_dow", values_from = "mean_hour") %>%
knitr::kable(digits = 3)
```

```{r}
data("brfss_smart2010") 
```

```{r} 
brfss_smart2010 %>% 
janitor::clean_names() 
```




